### ISSUE TITLE
Fix escaping list markers

### ISSUE THREAD

**Issue by michbart** [orchitech/gfm-escape#1]
GfmEscape is currently escaping ordered list marker `)`, which is valid ordered list marker according to [CommonMark spec](https://spec.commonmark.org/0.29/#ordered-list-marker). The second valid ordered list marker, `.`, is handled correctly.

**Comment by martincizek** [comment]
> GfmEscape is currently escaping ordered list marker `)`

OK, I guess the issue is that we actually do *NOT* escape it. :-)
